server:
  port: 8200
spring:
  application:
    name: ms-api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-product-service
              uri: http://localhost:8100
              predicates:
                - Path=/products/**, /categories/**, /product-db/h2-console/**

            - id: ms-payment-service
              uri: http://localhost:8125
              predicates:
                - Path=/payments/**, /payment-db/h2-console/**

            - id: ms-order-service
              uri: http://localhost:8150
              predicates:
                - Path=/orders/**, /order-db/h2-console/**