server:
  port: 8125

spring:
  application:
    name: ms-payment

  datasource:
    url: jdbc:h2:mem:payment_db
    username: admin
    password: admin

  h2:
    console:
      enabled: true
      path: /payment-db/h2-console

  jpa:
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true